# Generated by Django 3.1.7 on 2021-03-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password1', models.TextField(max_length=20)),
                ('password2', models.TextField(max_length=20)),
            ],
        ),
    ]
