# Generated by Django 3.1.7 on 2021-03-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20210309_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='details',
            name='password2',
        ),
    ]
